### PR TITLE
Discord sync

### PR DESCRIPTION
**Pull request by shaggyos**
* Pull request updates sink/__init__.py to resolve frozen route issue (already addressed in hangoutsbot/master
* Updated instructions in both discord.py as well as creating DISCORD.md.

### CODE REVIEW

**Review by neon-ninja — CHANGES_REQUESTED** [review]
The frozen route fix (https://github.com/neon-ninja/hangupsbot/pull/1/files/dd0753072ca8d8476eb0644ab94c2d68c7f02205#diff-978eca6b160200863f9de580e66a3719R148) seems outside the scope of the upstream discord_sync pull request

**Review by neon-ninja — CHANGES_REQUESTED** [review]
There seem to be a lot of � characters in DISCORD.md. Most concerningly, you advise people to surround their discord token with � on line 48 (https://github.com/neon-ninja/hangupsbot/pull/1/commits/dd0753072ca8d8476eb0644ab94c2d68c7f02205#diff-90a5bb4c1729154b620d537e208170c5R48)

**Comment by shaggyos** [comment]
Oops!  Must be some Unicode chars from the copy paste from my original
attempt to update.
I'll go through and fix it up.

**Comment by neon-ninja** [comment]
I've cherry picked your commits and added them to my discord_sync branch, so they're now showing in my upstream PR at https://github.com/hangoutsbot/hangoutsbot/pull/636

I did it that way because I expect https://github.com/neon-ninja/hangupsbot/pull/1/commits/c2f1375169ac973def9e2d7162087ad5fcb0aa43 would have a merge conflict with https://github.com/hangoutsbot/hangoutsbot/pull/655/commits/8192f7a4573b081ab86606624cdfe45e120d669b

Thanks for contributing!

**Review by neon-ninja — APPROVED** [review]

**Pull request closed without merging**
